@startuml
object Kunde {
+Kontaktinformationer
+Balance i DKK
}
object Kurv {
(Kurven kan indeholde 0 eller 1 ordrer)
}
object Ordre {
+Ordrenr.
+Dato
+Total pris
}
object Ordrelinje {
+Bund
+Top
+Antal
+Pris for dette antal
}
object Cupcake
object Bund {
+Navn
+Pris
}
object Top {
+Navn
+Pris
}

Kunde "1" -- "0..*" Ordre
Ordre "1" -- "1..*" Ordrelinje
Ordrelinje "1" -- "1" Cupcake
Cupcake "0..*" -- "1" Bund
Cupcake "0..*" -- "1" Top

@enduml